### ISSUE TITLE
Enhancement - Add Google Cloud Storage Support

### ISSUE THREAD

**Issue by ardabeyazoglu** [twindb/backup#152]
Hi,

I need to store my backups in google cloud storage, which is also popular. I can implement it, if you point me to amazon-s3 files.

**Comment by akuzminsky** [comment]
Hi @ardabeyazoglu ,

sounds like a complicated task for an external contributor, but I appreciate your help!
Check out https://github.com/twindb/backup/blob/develop/twindb_backup/destination/s3.py .
Basically, you would need to base a destination class GCS on BaseDestination, and implement abstract methods for google cloud storage. if you could do that I would add the logic to use the GCS class if the user defines google cloud as a destination in the config. 
please let me know if you have any questions.

**Comment by ardabeyazoglu** [comment]
Thanks @akuzminsky, I checked a bit and there is more work then I thought but I ll try to do it when i have time.

**Comment by ardabeyazoglu** [comment]
Hi @akuzminsky,

I managed to implement GCS storage, will add unit tests as well, but I don't know how to test it since I haven't used vagrant before. Python is also not my primary language, so i need a bit help here. Could you elaborate the steps how you usually test new features in this repo, so I can move on ? I may add some new features after this one, as well.

**Comment by akuzminsky** [comment]
Hi @ardabeyazoglu ,

Thank you for working on this. I'll be happy to merge GCP support.
You can write/run unit tests in a virtual environment on your dev machine - it doesn't have to vagrant (about it - later on).

All unit tests go into `tests/unit`. All GCP tests would be stored in `tests/unit/destination/gcp`, same pattern as `tests/unit/destination/s3`. I prefer to put all tests of same method in one file, for example `tests/unit/destination/s3/test_get_file_content.py`.

To create python virtual environment you would need to install and configure [virtualenvwrapper]([url](https://virtualenvwrapper.readthedocs.io/en/latest/)). Assuming you have done that:

Create the virtual environment. This is one time operation.
```
[08:35:51 aleks@Aleksandrs-MacBook-Pro backup]$ mkvirtualenv twindb-backup
New python executable in /Users/aleks/.virtualenvs/twindb-backup/bin/python2.7
Also creating executable in /Users/aleks/.virtualenvs/twindb-backup/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/aleks/.virtualenvs/twindb-backup/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/aleks/.virtualenvs/twindb-backup/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/aleks/.virtualenvs/twindb-backup/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/aleks/.virtualenvs/twindb-backup/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/aleks/.virtualenvs/twindb-backup/bin/get_env_details
(twindb-backup) [08:36:04 aleks@Aleksandrs-MacBook-Pro backup]$
```
If you continue work next day you can just "activate" the environment:
```
[08:37:43 aleks@Aleksandrs-MacBook-Pro backup]$ workon twindb-backup
(twindb-backup) [08:37:53 aleks@Aleksandrs-MacBook-Pro backup]$
```

Once you are in the virtual environment you should install twindb backup in it + twindb-backup's dependencies:
```
$ make bootstrap
...
Installing collected packages: twindb-backup
  Running setup.py develop for twindb-backup
Successfully installed twindb-backup
...
$
```

Now you can write unit tests and run them.
To run full test suite
```
$ make test
```
To run linter
```
$ make lint
```
To run a subset of tests
```
$ pytest -xvvs tests/unit/destination/s3
```

To run an individual test 
```
$ pytest -xvvs tests/unit/destination/s3/test_get_file_content.py::test_get_file_content_retry
```


About vagrant. I use it only for development tests and to run manually integration tests (master1 runs docker service). Normally you don't need vagrant machines, but it's handy to have a linux machine with MySQL. You can, for example, run the tool with GCP config to see how it really works. It is useful to write unit tests when you need to mock external components like S3 or GCP.

I also can help you writing the tests. Why don't you publish your code on GitHub? I will write tests and create PRs into your repo/branch. And when the feature is ready to go you will create a PR into twindb-backup/develop.

**Comment by ardabeyazoglu** [comment]
Hi @akuzminsky,

Much thanks for detailed explanation. I already had a pyenv, so i ll move on with it. I need to do some basic testing of what I wrote so far and then push it to the remote so you can contribute as well.

**Comment by ardabeyazoglu** [comment]
Hi @akuzminsky,

I pushed my modifications to https://github.com/ardabeyazoglu/twindb-mysql-backup. I took S3 class as an example, so the code is as similar as possible. Tested manually each method with my gcs account to make sure they work as expected, however unit tests are missing (I could help here as well, but i couldn't find *moto_s3* like mocks for gcs).
