### ISSUE TITLE
Packagecloud repository is gone

### ISSUE THREAD

**Issue by metaxy** [twindb/backup#194]
* TwinDB Backup version: any
* Operating System: Debian 9.9

### Description
`apt-get upgrade` fails because the repository at `https://packagecloud.io/twindb/main/debian` is returning a 404

See also [https://packagecloud.io/twindb/](https://packagecloud.io/twindb/).

![Screenshot_20190718_073001](https://user-images.githubusercontent.com/82704/61431470-e01b0380-a92d-11e9-8689-fc1312658776.png)

**Comment by akuzminsky** [comment]
I don't plan to provide a repo or packages any time soon.
As a workaround you can build a package on a machine with docker:

```
export PLATFORM=debian
export OS_VERSION=stretch
make package
```
The packages will be in `omnibus/pkg/`

**Comment by metaxy** [comment]
Then the readme should be updated. See https://github.com/twindb/backup/blob/develop/README.rst
