### ISSUE TITLE
Prevent multiple twindb-backup processes from running simultaneously (pid file/lock file)

### ISSUE THREAD

**Issue by ernstae** [twindb/backup#195]
* TwinDB Backup version: 2.18.3
* Operating System: CentOS 7.7

### Description
Using the crontab methodology doesn't guarantee that your hourly backups don't collide or conflict with your daily backups.  There appears to be no lock mechanism to prevent multiple processes from starting and overlapping.

This could obviously be handled from outside the program, but ideally, it would have a lock-file/pid-file that would prevent multiple processes from running.

### What I Did
Observed multiple processes running from CRON for both day and hour.

```
root       2513  0.0  0.0 126316  1648 ?        Ss   Oct18   0:06 /usr/sbin/crond -n
root      20404  0.0  0.0 196732  2636 ?        S    00:00   0:00  \_ /usr/sbin/CROND -n
root      20407  0.0  0.0 113176  1220 ?        Ss   00:00   0:00  |   \_ /bin/sh -c twindb-backup  backup daily 2>&1 | grep -v WARNING >> /var/log/twindb/backup.log
root      20409  0.0  0.0 267788 43560 ?        S    00:00   0:01  |       \_ /opt/twindb-backup/embedded/bin/python /usr/bin/twindb-backup backup daily
root      20410  0.0  0.0 112708   968 ?        S    00:00   0:00  |       \_ grep -v WARNING
root      20405  0.0  0.0 196732  2636 ?        S    00:00   0:00  \_ /usr/sbin/CROND -n
root      20408  0.0  0.0 113176  1220 ?        Ss   00:00   0:00  |   \_ /bin/sh -c twindb-backup  backup hourly 2>&1 | grep -v WARNING >> /var/log/twindb/backup.log
root      20411  1.8  0.3 917324 218908 ?       Sl   00:00   0:44  |       \_ /opt/twindb-backup/embedded/bin/python /usr/bin/twindb-backup backup hourly
root      28532 11.3  0.1 648904 104504 ?       Sl   00:21   2:04  |       |   \_ /usr/bin/xtrabackup --defaults-file=/root/.my.cnf --stream=xbstream --backup --target-dir . --incremental-basedir . --incremental-lsn=212923478577
root      28533 80.6  0.0   4620   608 ?        S    00:21  14:41  |       |   \_ gzip -9 -c -
root      20412  0.0  0.0 112708   968 ?        S    00:00   0:00  |       \_ grep -v WARNING
```

**Comment by akuzminsky** [comment]
There is a locking mechanism.
When the tool starts it grabs a lock on the pid file.
If other instance of the tool is already running, the tool will wait until the lock becomes available.
The lock wait time depends on run type - hourly backups will wait 30 mins, daily - 12 hours and so on.
CRON obviously can start multiple instances (especially if it is Sunday, 1st January). They all will be serialized.

What you see in the processes list is the hourly job started and the daily job is waiting.

See relevant part of the code https://github.com/twindb/backup/blob/develop/twindb_backup/backup.py#L376


P.S.
Interesting you are grepping out warnings - I guess you don't want CRON send you them. What are those messages you think useless?

**Comment by ernstae** [comment]
@akuzminsky - Thanks for taking the time to point out the lock wait mechanism.  As an end-user, I guess I was expecting to see some output indicating that the second process was waiting on the first.  

Our crontab output has a mail handler that ships any stderr to a team email alias, and it was really noisy with warnings at one point in time (early on, there were some problems with xtrabackup 8.0.x and I was suppressing warnings due to the frequency of our backup runs & resultant e-mail messages).  I'm passing `twindb-backup` the extra arguments to use `--xtrabackup-binary=/usr/bin/xtrabackup` for our MySQL 8.0 servers, and have been having pretty good luck with that (_though restores do not prepare correctly when using `twindb-backup restore... `, so once the files are dropped back on the server, an `/usr/bin/xtrabackup --prepare` step needs to happen.  I've been meaning to find time to make an issue + associated PR so that the restore process doesn't attempt to use the embedded xtrabackup program if an external binary is in the args for twind-backup. 

That said, thank you for your explanation.  I'll close this one out now!

**Comment by ernstae** [comment]
@akuzminsky - A proposed fix for being able to use xtrabackup 8.x on the command line for restore options is in #196
