### ISSUE TITLE
Unable to install via script.deb.sh

### ISSUE THREAD

**Issue by minkbear** [twindb/backup#203]
* TwinDB Backup version:
* Operating System: Ubuntu

### Description

unable to install. Page was moved

### What I Did

"The page you were looking for doesn't exist." on https://packagecloud.io/install/repositories/twindb/main/script.deb.sh

**Comment by akuzminsky** [comment]
I don't provide packages anymore, sorry.
As a workaround you can build them manually on a machine with docker (Linux or MacOS).
```
$ export PLATFORM=ubuntu
$ export OS_VERSION=bionic
$ make package
```

Relevant code - https://github.com/twindb/backup/blob/develop/Makefile#L192

**Comment by minkbear** [comment]
@akuzminsky thanks for your advice. But I got the error shown below please advice.

![image](https://user-images.githubusercontent.com/233714/71639329-31823980-2ca7-11ea-8ebf-f226d6af5c6f.png)

**Comment by akuzminsky** [comment]
Killed - it must be run out of memory.

**Comment by akuzminsky** [comment]
Might be relevant https://stackoverflow.com/questions/30887143/make-j-8-g-internal-compiler-error-killed-program-cc1plus
