### ISSUE TITLE
Fix for ssh destination delete issues

### ISSUE THREAD

**Issue by kr31n3r** [twindb/backup#210]
* TwinDB Backup version: 2.18.3
* Operating System: debian 9.9

### Description

As already issued in #149 and #193 delete actions via ssh are failing due to missing `remote_path` prefixes:
https://github.com/twindb/backup/blob/f7269d313484a9151227d70883c57ce596b19acb/twindb_backup/destination/ssh.py#L93

### Fix
The following changes should fix this issue:
```diff
<         cmd = "rm %s" % path
---
>         remote_name = osp.join(
>             self.remote_path,
>             path
>         )
>         cmd = "rm %s" % remote_name
```

**Comment by akuzminsky** [comment]
Fixed in 2.20.1
