### ISSUE TITLE
Manual is incorrect

### ISSUE THREAD

**Issue by ethaniel** [twindb/backup#317]
https://twindb-backup.readthedocs.io/en/stable/installation.html

I try to do `curl -s https://packagecloud.io/install/repositories/TwinDB/main/script.rpm.sh | sudo bash` as instructed, but get:
```
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE html>'
```

**Comment by akuzminsky** [comment]
You must be referring to an old version of the installation guide. In the past indeed I distributed twindb-backup via a third-party repo provider. Now you have to build a package.

The [link](https://twindb-backup.readthedocs.io/en/stable/installation.html) you posted says:


> TwinDB Backup can be installed from a DEB/RPM package. The TwinDB Backup package can build on a machine with Docker service.
> `make package` will build the package for the operating system defined in the `OS_VERSION` environment variable.
```
