### ISSUE TITLE
Releases not available anymore

### ISSUE THREAD

**Issue by chrisvanmeer** [twindb/backup#324]
It seems that the S3 bucket is no longer existent.  
I would like to download the package for Ubuntu Focal, but none of the links work.  
  
Anybody that has a twindb-backup package for Ubuntu 20.04?

**Comment by akuzminsky** [comment]
Fixed. The package for focal is available on https://twindb-release.s3.amazonaws.com/twindb-backup/2.20.2/focal/twindb-backup_2.20.2-1_amd64.deb
