### ISSUE TITLE
No RPMs available

### ISSUE THREAD

**Issue by cjsfj** [twindb/backup#37]
* TwinDB Backup version: n/a
* Python version: 2.6.6
* Operating System: Oracle Linux 6.8

### Description

I was trying to install twins

### What I Did

After the install process ran, I ran yum install twindb-backup (per the docs)

Here is the output:

```
# yum install twindb-backup
Loaded plugins: priorities, security, ulninfo
Setting up Install Process
536 packages excluded due to repository priority protections
No package twindb-backup available.
Error: Nothing to do
```

Is anyone having this issue? Seems that the RPM repo is empty.

**Comment by akuzminsky** [comment]
There are no packages because we don't support version 6.
The supported versions are
* RedHat/CentOS 7
* Ubuntu trusty
* Debian jessie

**Comment by cjsfj** [comment]
Got it. Sorry I missed that!
