### ISSUE TITLE
Continue support for CentOS 7 Releases till CentOS EOL in June 2024

### ISSUE THREAD

**Issue by ernstae** [twindb/backup#409]
## Background
In 2020, The CentOS Project, in coordination with Red Hat, announced that it would shift full investment to CentOS Stream, the upstream development platform for upcoming Red Hat Enterprise Linux releases. As a result, CentOS Linux 7 will reach end of life (EOL) on June 30, 2024. 
https://www.redhat.com/en/topics/linux/centos-linux-eol

## Problem
It appears that CentOS 7 support has already been removed from the twindb/backup project in release 3.2.0.  Is it possible to continue support until the EOL date of the OS?  Additionally, some organizations would likely wish to continue RPM availability for the releases -- so ensuring the build and scripts continue to support RPM-based systems would be ideal/appreciated even post EOL of CentOS 7 (e.g. RHEL 8 and beyond)

**Comment by akuzminsky** [comment]
fixed in https://github.com/twindb/backup/releases/tag/3.3.0
