### ISSUE TITLE
AttributeError: 'int' object has no attribute 'lower'

### ISSUE THREAD

**Issue by fonthead** [twindb/backup#49]
* TwinDB Backup version: 2.14.0
* Python version: 2.7.12
* Operating System: Ubnutu Server 16.04.3 LTS

### Description

There is a small bug in the source:

File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.14.0-py2.7.egg/twindb_backup/source/mysql_source.py", line 447

I get a python error:

AttributeError: 'int' object has no attribute 'lower'

### What I Did

```
Lines 446 & 447:

                   return (str(row['wsrep_on']).lower() == "1" or
                            row['wsrep_on'].lower() == 'on')

Should be fixed by doing this:

                   return (str(row['wsrep_on']).lower() == "1" or
                            str(row['wsrep_on']).lower() == 'on')
```

Can you please update the code with this change? Otherwise, I have to edit this file everytime it updates.

**Comment by mkryva** [comment]
https://github.com/twindb/backup/pull/64
