### ISSUE TITLE
 2016-12-05 02:30:55,823: ERROR: restore.restore_from_mysql_full():68: Failed to unarchive s3://*****/daily/mysql/mysql-2016-12-01_01_13_55.xbstream.gz: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by akuzminsky** [twindb/backup#5]
* TwinDB Backup version: 2.4.0

### Description

If xtrabackup isn't present on the system `twindb-backup` will exit with error `2016-12-05 02:30:55,823: ERROR: restore.restore_from_mysql_full():68: Failed to unarchive s3://****/daily/mysql/mysql-2016-12-01_01_13_55.xbstream.gz: [Errno 2] No such file or directory
`
### What I Did

```
twindb-backup restore mysql s3://****/daily/mysql/mysql-2016-12-01_01_13_55.xbstream.gz
```

### Workaround

Install Percona Xtrabackup
```
# yum install http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm
# yum install percona-xtrabackup
```
### Solution

List xtrabackup as a dependency

**Comment by ovaistariq** [comment]
Xtrabackup is now listed as a dependency in the package.
