### ISSUE TITLE
twindb-backup clone mysql shouldn't stop MySQL on destination

### ISSUE THREAD

**Issue by akuzminsky** [twindb/backup#53]
* TwinDB Backup version: 2.14.1

### Description

`clone mysql` attempts to stop MySQL on the destination. It shouldn't. 
Instead it should check if MySQL is running and raise an exception if it is.

**Comment by mkryva** [comment]
https://github.com/twindb/backup/pull/56

**Comment by mkryva** [comment]
Fixed in https://github.com/twindb/backup/issues/61

**Comment by akuzminsky** [comment]
looks like the bug is not fixed

```
2017-11-09 13:53:22,807: ERROR: clone.clone_mysql():85: Failed to stop MySQL on <twindb_backup.destination.ssh.Ssh object at 0x7f8076317d90>
$ twindb-backup --version
2.14.4
```

**Comment by mkryva** [comment]
https://github.com/twindb/backup/pull/74
