### ISSUE TITLE
if backup job fails remove artifacts

### ISSUE THREAD

**Issue by akuzminsky** [twindb/backup#8]
* TwinDB Backup version: 2.5.0

### Description

A backup job failed because of xtrabackup error:
```
170103 21:39:05 Executing FLUSH NO_WRITE_TO_BINLOG TABLES...
170103 21:39:05 Executing FLUSH TABLES WITH READ LOCK...
Error: failed to execute query FLUSH TABLES WITH READ LOCK: Lock wait timeout exceeded; try restarting transaction
```
The tool didn't save a status record (which is expected), but it also left a backup copy in S3 which is in unknown state, I don't know if it's usable or not. 
The tool should exit gracefully and do some clean-up.

**Comment by mkryva** [comment]
https://github.com/twindb/backup/pull/43
