### ISSUE TITLE
Local retention policy is not respected

### ISSUE THREAD

**Issue by akuzminsky** [twindb/backup#80]
* TwinDB Backup version: 2.15.0

### Description

TwinDB Backup can keep few latest copies on the same server it takes backups from. The feature is enabled by `keep_local_path` options.

The local copies have their own retention policy managed by `[retention_local]` section in `/etc/twindb/twindb-backup.conf`.

There is a report from a user that the local retention policy in version 2.15.0 is not respected and the tool fills local disk with backup copies.

A workaround to this is to disable `keep_local_path`.

We need to reproduce the bug, write a unit test (possibly integration test as well) and fix the bug.

**Comment by mkryva** [comment]
I can't represent this bug. I tried to represent it on backups files and mysql, but I hadn't found this problem. When I had disabled `keep_local_path`, backups weren't  saved locally. And If this option is enabled, backups are saved locally according to `retention_local`
