### ISSUE TITLE
Where/How should I set if backup type should be full or incremental?

### ISSUE THREAD

**Issue by catyellow** [twindb/backup#84]
* TwinDB Backup version: latest
* Python version: -
* Operating System: -

### Description

Hi guys,

I'm reading the docs here: https://twindb-backup.readthedocs.io/
I see that full/incremental types of backups are supported, but I can't find in the docs where and how should I set such type. 

Thanks.
Best, Michael Rikmas

**Comment by akuzminsky** [comment]
Hey Mixa!

In `mysql` section you specify how often you want to do full backups
```
[mysql]
# MySQL
mysql_defaults_file=/root/.my.cnf
full_backup=daily
```
Then any more frequent job will take incremental copy.
For example, If it's daily then twindb-backup will take full copy every day and incremental copy every hour.

**Comment by catyellow** [comment]
Alex, thanks for quick help!
All clear now.
